name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Cài đặt Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # hoặc bạn có thể ghi cụ thể phiên bản bạn muốn
      
      # Build Flutter web
      - name: Build Flutter web
        run: flutter build web --release
      
      # Deploy lên Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_EMAIL_APP_2025 }}
          channelId: live
          projectId: flutter-email-app-2025
